### ISSUE TITLE
W/GAv4    (30377): AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.

### ISSUE THREAD

**Issue by smks** [SempaiGames/haxe-ga#21]
W/GAv4    (30377): AnalyticsService not registered in the app manifest. Hits might not be delivered reliably. See http://goo.gl/8Rd3yj for instructions.

**Comment by fbricker** [comment]
Hi, are you getting this message on your logs? If this is the case, maybe you're using some Google Analytics native extension or integrating this yourself.

haxe-ga is a pure Haxe implementation of Google Analytics API for websites, and it does not includes the Google Analytics native SDK for android or iOS (so AnalyticsApplication permission is not required since this extension does not offer Screen Interaction Analytics and other native features).

PS: Now we're on this topic, I think it'll be nice to integrate native SDKs to be able to provide better features with the extensions, but I don't have much time left to do it. If anyone can do this, will be much appreciated.
